In [2]:
import numpy as np
lst =  [
    [1, 2, 3],
    [4, 5, 6]
]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
scalar = 1
scalar

In [3]:
vector= np.array([1, 4, 5, 6])
vector

array([1, 4, 5, 6])

In [4]:
vector.dtype

dtype('int32')

In [5]:
arr.size

6

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [14]:
rg = np.random.defalut_rng(1)

AttributeError: module 'numpy.random' has no attribute 'defalut_rng'

In [12]:
np.floor(10*rg_random((2,2)))

NameError: name 'rg_random' is not defined

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr1 = np.array([[1, 1],
               [2, 2]])
arr2 = np.array([[3, 3],
               [4, 4]])

In [28]:
arrv = np.vstack((arr1, arr2))
arrv

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [26]:
arrh = np.hstack((arr1, arr2))
arrh 

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# 차원 변환

In [21]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr2 = np.expand_dims(arr, axis=0)
arr2.shape

(1, 20)

In [30]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [31]:
arr.resize((5, 4))

In [34]:
arr.reshape(4, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [35]:
arr = np.arange(20)
type(arr)

numpy.ndarray

In [37]:
arr.dtype # arr의 데이터 자료형 확인

dtype('float32')

In [36]:
arr = arr.astype(np.float32) # 데이터 타입 변환
arr.dtype 

dtype('float32')

In [38]:
np.power(100, 8, dype-np.int64)
arr.dtype, arr

NameError: name 'dype' is not defined

In [39]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [41]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [42]:
arr[1], arr[-1]

(1.0, 19.0)

In [43]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr[arr < 5]

array([1, 2, 3, 4])

In [45]:
cond = (arr >= 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [47]:
cond = ( arr > 5) | (arr == 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
# np.any: 조건에 참이 하나라도 있으면, True
np.any(arr > 5)

True

In [49]:
# np.where(조건, 참인 경우, 거짓 경우)
np.where(arr>5, 1, 0)

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.clip(arr, 5, 8)

array([[5, 5, 5, 5],
       [5, 6, 7, 8],
       [8, 8, 8, 8]])

In [51]:
is_inf = np.isnan(arr)
np.any(is_nan), np.all(is_nan)

NameError: name 'is_nan' is not defined

In [52]:
np.isfinite(arr)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
arr[np.isfinite(arr) == False]

array([], dtype=int32)

# 마스킹

In [54]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
arr.shape

(3, 3)

In [55]:
mask = [True,False,True]
arr[:,mask]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [56]:
mask = arr > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [57]:
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([2.0, 2.0, 2.0])
arr1 * arr2

array([2., 4., 6.])

In [58]:
arr1 = np.array([
    [0.0, 0.0, 0.0],
    [10.0, 10.0, 10.0],
    [20.0, 20.0, 20.0],
    [30.0, 30.0, 30.0]
])
arr2 = np.array([1.0, 2.0, 3.0])
arr1 + arr2

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])